stages:
  - build

build_job:
  stage: build
  script:
  - ls
  - 'echo restoring nuget...'
  - .\nuget.exe restore Common\Common.sln
  - 'echo building...'
  - 'msbuild Common\Common.sln /p:Configuration=Debug /p:Platform="Any CPU"'
  except:
  - tags