image: mono:latest

variables:
  PROJ_NAME: 'Common'
  UT_PREFIX: 'UnitTestCommon'
  TEST_RUNNER: 'NUnit.ConsoleRunner'
  TEST_RUNNER_W_VER: 'NUnit.ConsoleRunner.3.9.0'
  BUILD_CONF: 'Debug'

stages:
  - build
  - test

build_job:
  stage: build
  script:
  - 'nuget restore ${PROJ_NAME}/${PROJ_NAME}.sln'
  - 'MONO_IOMAP=case msbuild /t:Build /p:Configuration=Debug /p:Platform="Any CPU" ${PROJ_NAME}/${PROJ_NAME}.sln'
  cache:
    key: binaries
    paths:
    - 'bin/Tests/Debug/'
  except:
  - tags

test_job:
  stage: test
  cache:
    key: binaries
    paths:
    - 'bin/Tests/Debug'
    policy: pull
  script:
  - 'apt-get -qq update -y'
  - 'apt-get -qq install unzip'
  - 'nuget install ${TEST_RUNNER}'
  - 'unzip ${TEST_RUNNER_W_VER}/${TEST_RUNNER_W_VER}.nupkg'
  - 'chmod -R 777 tools'

  - 'for i in $(ls bin/Tests/Debug/*.dll | egrep ^*/UnitTestCommon*); do mono tools/nunit3-console.exe $i; done'
  except:
  - tags