variables:
    - nuget: 'C:\GitLab-Runner\nuget.exe'

stages:
  - build

build_job:
  stage: build
  script:
  - ls Common
  - 'echo restoring nuget...'
  - '%nuget% restore Common\Common.sln'
  - 'echo building...'
  - 'msbuild Common\Common.sln /p:Configuration=Debug /p:Platform="Any CPU"'
  except:
  - tags