image: mono:latest

stages:
  - build

build_job:
  stage: build
  script:
  - 'echo restoring nuget...'
  - 'nuget restore Common/Common.sln'
  - 'echo building...'
  - 'MONO_IOMAP=case msbuild /t:Build /p:Configuration=Debug /p:Platform="Any CPU" Common/Common.sln'
